"use client";

import { jsPDF } from "jspdf";

type RgbColor = [number, number, number];

interface PdfColors {
  primary: RgbColor;
  accent: RgbColor;
  gray: RgbColor;
  lightBg: RgbColor;
  border: RgbColor;
  footer: RgbColor;
  white: RgbColor;
  green: RgbColor;
  amber: RgbColor;
  red: RgbColor;
}

const C: PdfColors = {
  primary: [15, 23, 42],
  accent: [37, 99, 235],
  gray: [100, 116, 139],
  lightBg: [241, 245, 249],
  border: [226, 232, 240],
  footer: [148, 163, 184],
  white: [255, 255, 255],
  green: [5, 150, 105],
  amber: [217, 119, 6],
  red: [220, 38, 38],
};

const PAGE_W = 210;
const MARGIN = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;

interface PageState {
  pageNum: number;
}

// ── Draw page header ───────────────────────────────────────────
function drawHeader(pdf: jsPDF, title: string, subtitle: string) {
  pdf.setFillColor(...C.primary);
  pdf.rect(0, 0, PAGE_W, 45, "F");
  pdf.setTextColor(...C.white);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("NEXYOVI", MARGIN, 22);
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "normal");
  pdf.text("AI-Powered Business OS \u2022 Document Management", MARGIN, 32);
  pdf.setTextColor(...C.white);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  pdf.text(subtitle, PAGE_W - MARGIN, 22, { align: "right" });
}

// ── Draw page footer ───────────────────────────────────────────
function drawFooter(pdf: jsPDF, ps: PageState) {
  pdf.setDrawColor(...C.border);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN, 285, PAGE_W - MARGIN, 285);
  pdf.setTextColor(...C.footer);
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "normal");
  pdf.text(
    `Generated by NEXYOVI Document Management \u2022 ${new Date()
      .toISOString()
      .split("T")[0]}`,
    MARGIN,
    291
  );
  pdf.text(`Page ${ps.pageNum}`, PAGE_W - MARGIN, 291, {
    align: "right",
  });
}

// ── Add new page with header/footer ─────────────────────────────
function addPage(pdf: jsPDF, ps: PageState, title: string): number {
  ps.pageNum++;
  pdf.addPage();
  drawHeader(pdf, title, `${ps.pageNum}`);
  drawFooter(pdf, ps);
  return 55;
}

// ── Draw colored section badge ─────────────────────────────────
function drawSectionBadge(
  pdf: jsPDF,
  label: string,
  color: RgbColor,
  yPos: number
) {
  pdf.setFillColor(...color);
  const bw = pdf.getTextWidth(label) + 10;
  pdf.roundedRect(MARGIN, yPos - 4, bw, 12, 3, 3, "F");
  pdf.setTextColor(...C.white);
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "bold");
  pdf.text(label, MARGIN + 5, yPos + 4);
  pdf.setTextColor(...C.primary);
  pdf.setFontSize(9);
}

// ── Draw info row with alternating background ───────────────────
function drawInfoRow(
  pdf: jsPDF,
  label: string,
  value: string,
  yPos: number,
  even = false
): number {
  if (even) {
    pdf.setFillColor(...C.lightBg);
    pdf.rect(MARGIN, yPos, CONTENT_W, 10, "F");
  }
  pdf.setTextColor(...C.gray);
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "bold");
  pdf.text(label, MARGIN + 4, yPos + 7);
  pdf.setTextColor(...C.primary);
  pdf.setFont("helvetica", "normal");
  pdf.text(String(value || "\u2014"), MARGIN + CONTENT_W * 0.35, yPos + 7);
  return yPos + 10;
}

// ── Draw progress bar ──────────────────────────────────────────
function drawProgressBar(
  pdf: jsPDF,
  label: string,
  pct: number,
  yPos: number,
  barColor: RgbColor
): number {
  pdf.setTextColor(...C.gray);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  pdf.text(label, MARGIN, yPos);
  pdf.setDrawColor(...C.border);
  pdf.setFillColor(241, 245, 249);
  pdf.roundedRect(MARGIN, yPos + 3, CONTENT_W, 5, 2, 2, "FD");
  if (pct > 0) {
    pdf.setFillColor(...barColor);
    pdf.roundedRect(
      MARGIN,
      yPos + 3,
      CONTENT_W * Math.min(1, pct / 100),
      5,
      2,
      2,
      "F"
    );
  }
  pdf.setTextColor(...C.primary);
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "bold");
  pdf.text(`${Math.round(pct)}%`, MARGIN + CONTENT_W - 15, yPos);
  return yPos + 14;
}

// ── Draw KPI card ──────────────────────────────────────────────
function drawKpiCard(
  pdf: jsPDF,
  label: string,
  value: string,
  x: number,
  yPos: number,
  cardColor: RgbColor
) {
  const cardW = (CONTENT_W - 12) / 3;
  pdf.setFillColor(...cardColor);
  pdf.roundedRect(x, yPos, cardW, 24, 4, 4, "F");
  pdf.setTextColor(...C.primary);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  pdf.text(label, x + 6, yPos + 10);
  pdf.setTextColor(...C.white);
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.text(String(value), x + 6, yPos + 21);
}

// ── Render a single document's report pages ─────────────────────
export function renderDocPages(
  pdf: jsPDF,
  doc: any,
  ps: PageState,
  allData: {
    storageData: any[];
    versionsData: any[];
    signaturesData: any[];
    ocrData: any[];
    aiSearchData: any[];
  }
): string {
  const { storageData, versionsData, signaturesData, ocrData, aiSearchData } =
    allData;
  const docName = doc.document || "Untitled Document";

  // ── PAGE 1: Document Details ──────────────────────────────
  drawHeader(pdf, "Document Report", `${ps.pageNum}`);
  drawFooter(pdf, ps);
  let y = 55;
  pdf.setTextColor(...C.primary);
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");
  pdf.text(docName, MARGIN, y);
  y += 5;
  pdf.setDrawColor(...C.accent);
  pdf.setLineWidth(2);
  pdf.line(MARGIN, y, MARGIN + Math.min(120, pdf.getTextWidth(docName) + 10), y);
  y += 12;

  const docTitle = (doc.document || doc.title || doc.name || "")
    .toLowerCase()
    .trim();
  const relStorage = storageData.find(
    (s: any) => (s.title || s.name || "").toLowerCase().includes(docTitle)
  );
  const relVersions = versionsData.filter((v: any) =>
    (v.document || "").toLowerCase().includes(docTitle)
  );
  const relSigs = signaturesData.filter((s: any) =>
    (s.document || "").toLowerCase().includes(docTitle)
  );
  const relOcr = ocrData.filter((o: any) =>
    (o.document || "").toLowerCase().includes(docTitle)
  );
  const relAi = aiSearchData.filter((a: any) =>
    (a.document || "").toLowerCase().includes(docTitle)
  );

  drawSectionBadge(pdf, "DOCUMENT INFO", C.accent, y);
  y += 16;
  const infoRows = [
    { label: "Document", value: docName },
    { label: "Source Format", value: doc.fileType || relStorage?.fileType || "N/A" },
    { label: "Output Format", value: doc.format || "PDF" },
    { label: "File Size", value: doc.size || (relStorage?.size ? `${relStorage.size}` : "N/A") },
    { label: "Category", value: relStorage?.category || "N/A" },
    { label: "Owner", value: relStorage?.owner || doc.owner || "N/A" },
    { label: "Tags", value: relStorage?.tags || "N/A" },
    { label: "Last Modified", value: relStorage?.modified || "N/A" },
    { label: "Status", value: doc.status || relStorage?.status || "Draft" },
    {
      label: "Version",
      value: `v${
        relVersions.length > 0
          ? Math.max(...relVersions.map((v: any) => v.version || 1))
          : doc.version || 1
      }`,
    },
    { label: "Generated On", value: new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) },
  ];
  infoRows.forEach((r, i) => {
    y = drawInfoRow(pdf, r.label, r.value, y, i % 2 === 0);
  });

  y += 8;
  pdf.setDrawColor(...C.border);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;
  pdf.setTextColor(...C.gray);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  pdf.text("RELATED MODULE OVERVIEW", MARGIN, y);
  y += 10;

  const moduleCards = [
    { label: "Versions", value: relVersions.length, color: C.accent },
    { label: "Signatures", value: relSigs.length, color: C.green },
    { label: "OCR Records", value: relOcr.length, color: C.amber },
    { label: "AI Indexed", value: relAi.filter((a: any) => a.status === "Indexed").length, color: C.primary },
  ];
  moduleCards.forEach((item, idx) => {
    const ecw = (CONTENT_W - 12) / 4;
    const cx = MARGIN + idx * (ecw + 4);
    pdf.setFillColor(...item.color);
    pdf.roundedRect(cx, y, ecw, 22, 4, 4, "F");
    pdf.setTextColor(...C.white);
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "bold");
    pdf.text(item.label, cx + 5, y + 9);
    pdf.setFontSize(13);
    pdf.text(String(item.value), cx + 5, y + 20);
  });

  // ── PAGE 2: Version History ──────────────────────────────
  if (relVersions.length > 0) {
    y = addPage(pdf, ps, "Version History");
    drawSectionBadge(pdf, "VERSION HISTORY", C.accent, y);
    y += 16;
    pdf.setFillColor(...C.primary);
    pdf.rect(MARGIN, y, CONTENT_W, 10, "F");
    pdf.setTextColor(...C.white);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "bold");
    pdf.text("Version", MARGIN + 4, y + 7);
    pdf.text("Change Log", MARGIN + 50, y + 7);
    pdf.text("By", MARGIN + 130, y + 7);
    pdf.text("Date", MARGIN + 165, y + 7);
    y += 10;
    relVersions.forEach((v: any, i: number) => {
      if (y > 260) {
        y = addPage(pdf, ps, "Version History (cont.)");
      }
      if (i % 2 === 0) {
        pdf.setFillColor(...C.lightBg);
        pdf.rect(MARGIN, y, CONTENT_W, 10, "F");
      }
      pdf.setTextColor(...C.primary);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.text(`v${v.version || 1}`, MARGIN + 4, y + 7);
      pdf.setFont("helvetica", "normal");
      pdf.text(
        String(v.changeLog || "\u2014").slice(0, 30),
        MARGIN + 50,
        y + 7
      );
      pdf.text(String(v.createdBy || "System"), MARGIN + 130, y + 7);
      pdf.text(
        String(v.createdAt || "").split("T")[0] || "\u2014",
        MARGIN + 165,
        y + 7
      );
      y += 10;
    });
  }

  // ── PAGE 3: Digital Signatures ──────────────────────────
  if (relSigs.length > 0) {
    y = addPage(pdf, ps, "Digital Signatures");
    drawSectionBadge(pdf, "DIGITAL SIGNATURES", C.green, y);
    y += 16;
    const sigDone = relSigs.filter(
      (s: any) => s.status === "Signed"
    ).length;
    const sigPct =
      relSigs.length > 0
        ? Math.round((sigDone / relSigs.length) * 100)
        : 0;
    y = drawProgressBar(
      pdf,
      "Signature Completion",
      sigPct,
      y,
      C.green
    );
    y += 6;
    const sigCards = [
      { label: "Total", value: relSigs.length, color: C.primary },
      { label: "Signed", value: sigDone, color: C.green },
      {
        label: "Pending",
        value: relSigs.filter((s: any) => s.status === "Pending")
          .length,
        color: C.amber,
      },
    ];
    sigCards.forEach((sc, idx) =>
      drawKpiCard(
        pdf,
        sc.label,
        String(sc.value),
        MARGIN + idx * ((CONTENT_W - 8) / 3 + 4),
        y,
        sc.color as RgbColor
      )
    );
    y += 32;
    pdf.setFillColor(...C.primary);
    pdf.rect(MARGIN, y, CONTENT_W, 10, "F");
    pdf.setTextColor(...C.white);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "bold");
    pdf.text("Request", MARGIN + 4, y + 7);
    pdf.text("Signer", MARGIN + 60, y + 7);
    pdf.text("Email", MARGIN + 105, y + 7);
    pdf.text("Status", MARGIN + 150, y + 7);
    pdf.text("Date", MARGIN + 180, y + 7);
    y += 10;
    relSigs.forEach((s: any, i: number) => {
      if (y > 260) {
        y = addPage(pdf, ps, "Digital Signatures (cont.)");
      }
      if (i % 2 === 0) {
        pdf.setFillColor(...C.lightBg);
        pdf.rect(MARGIN, y, CONTENT_W, 10, "F");
      }
      pdf.setTextColor(...C.primary);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      pdf.text(
        String(s.requestName || "Request").slice(0, 18),
        MARGIN + 4,
        y + 7
      );
      pdf.text(String(s.signerName || "\u2014"), MARGIN + 60, y + 7);
      pdf.text(
        String(s.signerEmail || "\u2014"),
        MARGIN + 105,
        y + 7
      );
      pdf.setFont("helvetica", "bold");
      pdf.text(
        String(s.status || "Pending"),
        MARGIN + 150,
        y + 7
      );
      pdf.setFont("helvetica", "normal");
      pdf.text(
        String(s.signedAt || "").split("T")[0] || "\u2014",
        MARGIN + 180,
        y + 7
      );
      y += 10;
    });
  }

  // ── PAGE 4: OCR & AI Status ─────────────────────────────
  if (relOcr.length > 0 || relAi.length > 0) {
    y = addPage(pdf, ps, "OCR & AI Processing");
    if (relOcr.length > 0) {
      drawSectionBadge(pdf, "OCR PROCESSING STATUS", C.amber, y);
      y += 16;
      const ocrDone = relOcr.filter(
        (o: any) => o.status === "Completed"
      ).length;
      y = drawProgressBar(
        pdf,
        "OCR Completion Rate",
        relOcr.length > 0
          ? Math.round((ocrDone / relOcr.length) * 100)
          : 0,
        y,
        C.amber
      );
      y += 10;
      pdf.setFillColor(...C.primary);
      pdf.rect(MARGIN, y, CONTENT_W, 10, "F");
      pdf.setTextColor(...C.white);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.text("File Type", MARGIN + 4, y + 7);
      pdf.text("Confidence", MARGIN + 70, y + 7);
      pdf.text("Pages", MARGIN + 110, y + 7);
      pdf.text("Status", MARGIN + 145, y + 7);
      y += 10;
      relOcr.forEach((o: any, i: number) => {
        if (y > 260) {
          y = addPage(pdf, ps, "OCR & AI (cont.)");
        }
        if (i % 2 === 0) {
          pdf.setFillColor(...C.lightBg);
          pdf.rect(MARGIN, y, CONTENT_W, 10, "F");
        }
        pdf.setTextColor(...C.primary);
        pdf.setFontSize(8);
        pdf.setFont("helvetica", "normal");
        pdf.text(
          String(o.fileType || "\u2014"),
          MARGIN + 4,
          y + 7
        );
        pdf.text(
          String(o.confidence || "\u2014"),
          MARGIN + 70,
          y + 7
        );
        pdf.text(String(o.pages || "\u2014"), MARGIN + 110, y + 7);
        pdf.setFont("helvetica", "bold");
        pdf.text(
          String(o.status || "Pending"),
          MARGIN + 145,
          y + 7
        );
        y += 10;
      });
    }
    if (relAi.length > 0) {
      y += 8;
      drawSectionBadge(pdf, "AI SEARCH INDEX STATUS", C.primary, y);
      y += 16;
      const aiDone = relAi.filter(
        (a: any) => a.status === "Indexed"
      ).length;
      y = drawProgressBar(
        pdf,
        "AI Indexing Rate",
        relAi.length > 0
          ? Math.round((aiDone / relAi.length) * 100)
          : 0,
        y,
        C.primary
      );
      y += 10;
      pdf.setFillColor(...C.primary);
      pdf.rect(MARGIN, y, CONTENT_W, 10, "F");
      pdf.setTextColor(...C.white);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.text("File Type", MARGIN + 4, y + 7);
      pdf.text("Confidence", MARGIN + 70, y + 7);
      pdf.text("Status", MARGIN + 120, y + 7);
      pdf.text("Indexed", MARGIN + 160, y + 7);
      y += 10;
      relAi.forEach((a: any, i: number) => {
        if (y > 260) {
          y = addPage(pdf, ps, "AI Search (cont.)");
        }
        if (i % 2 === 0) {
          pdf.setFillColor(...C.lightBg);
          pdf.rect(MARGIN, y, CONTENT_W, 10, "F");
        }
        pdf.setTextColor(...C.primary);
        pdf.setFontSize(8);
        pdf.setFont("helvetica", "normal");
        pdf.text(
          String(a.fileType || "\u2014"),
          MARGIN + 4,
          y + 7
        );
        pdf.text(
          String(a.confidence || "\u2014"),
          MARGIN + 70,
          y + 7
        );
        pdf.setFont("helvetica", "bold");
        pdf.text(String(a.status || "\u2014"), MARGIN + 120, y + 7);
        pdf.setFont("helvetica", "normal");
        pdf.text(
          String(a.lastIndexed || "\u2014").split("T")[0] || "\u2014",
          MARGIN + 160,
          y + 7
        );
        y += 10;
      });
    }
  }

  return docName;
}

// ── Draw dashboard summary page ────────────────────────────────
export function drawDashboardPage(
  pdf: jsPDF,
  ps: PageState,
  storageData: any[],
  versionsData: any[],
  signaturesData: any[],
  ocrData: any[],
  aiSearchData: any[],
  templatesData: any[],
  pdfData: any[],
  kpis: {
    totalDocs: number;
    pendingSigs: number;
    signedDocs: number;
    ocrCompleted: number;
    templates: number;
    totalSize: number;
    indexed: number;
  }
) {
  const C2: { [key: string]: RgbColor } = {
    primary: [15, 23, 42] as RgbColor,
    accent: [37, 99, 235] as RgbColor,
    gray: [100, 116, 139] as RgbColor,
    lightBg: [241, 245, 249] as RgbColor,
    border: [226, 232, 240] as RgbColor,
    footer: [148, 163, 184] as RgbColor,
    white: [255, 255, 255] as RgbColor,
    green: [5, 150, 105] as RgbColor,
    amber: [217, 119, 6] as RgbColor,
  };

  ps.pageNum++;
  pdf.addPage();
  pdf.setFillColor(...C2.primary!);
  pdf.rect(0, 0, PAGE_W, 45, "F");
  pdf.setTextColor(...C2.white!);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("NEXYOVI", MARGIN, 22);
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "normal");
  pdf.text(
    "AI-Powered Business OS \u2022 Document Management",
    MARGIN,
    32
  );
  pdf.setTextColor(...C2.white!);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  pdf.text(`Dashboard \u2022 P.${ps.pageNum}`, PAGE_W - MARGIN, 22, {
    align: "right",
  });

  let y = 55;
  const drawKpiCard2 = (
    label: string,
    value: string,
    x: number,
    yPos: number,
    color: RgbColor
  ) => {
    const cardW = (CONTENT_W - 12) / 3;
    pdf.setFillColor(...color);
    pdf.roundedRect(x, yPos, cardW, 24, 4, 4, "F");
    pdf.setTextColor(...C2.primary!);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "bold");
    pdf.text(label, x + 6, yPos + 10);
    pdf.setTextColor(...C2.white!);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text(String(value), x + 6, yPos + 21);
  };

  pdf.setTextColor(...C2.primary!);
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "bold");
  pdf.text("Document Management Dashboard", MARGIN, y);
  y += 5;
  pdf.setDrawColor(...C2.accent);
  pdf.setLineWidth(1.5);
  pdf.line(MARGIN, y, MARGIN + 100, y);
  y += 14;

  const kpiRows = [
    [
      { label: "Total Documents", value: storageData.length, color: C2.accent },
      {
        label: "Storage Used",
        value:
          kpis.totalSize >= 1024
            ? `${(kpis.totalSize / 1024).toFixed(1)} MB`
            : `${kpis.totalSize} KB`,
        color: C2.primary,
      },
      { label: "Templates", value: templatesData.length, color: C2.amber },
    ],
    [
      { label: "Signed", value: kpis.signedDocs, color: C2.green },
      { label: "Pending Signatures", value: kpis.pendingSigs, color: C2.amber },
      { label: "OCR Completed", value: kpis.ocrCompleted, color: C2.accent },
    ],
    [
      { label: "AI Indexed", value: kpis.indexed, color: C2.primary },
      { label: "Total Versions", value: versionsData.length, color: C2.accent },
      { label: "PDF Generated", value: pdfData.length, color: C2.green },
    ],
  ];

  kpiRows.forEach((row) => {
    row.forEach((k: any, idx: number) =>
      drawKpiCard2(
        k.label,
        String(k.value),
        MARGIN + idx * ((CONTENT_W - 8) / 3 + 4),
        y,
        k.color
      )
    );
    y += 32;
  });

  y += 4;    pdf.setDrawColor(...C2.border!);
    pdf.setLineWidth(0.5);
    pdf.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 8;
    pdf.setTextColor(...C2.gray!);
    pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  pdf.text("COMPLETION RATES", MARGIN, y);

  const drawPB = (
    label: string,
    pct: number,
    yPos: number,
    barColor: RgbColor
  ): number => {
    pdf.setTextColor(...C2.gray!);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.text(label, MARGIN, yPos);
    pdf.setDrawColor(...C2.border!);
    pdf.setFillColor(241, 245, 249);
    pdf.roundedRect(MARGIN, yPos + 3, CONTENT_W, 5, 2, 2, "FD");
    if (pct > 0) {
      pdf.setFillColor(...barColor);
      pdf.roundedRect(
        MARGIN,
        yPos + 3,
        CONTENT_W * Math.min(1, pct / 100),
        5,
        2,
        2,
        "F"
      );
    }
    pdf.setTextColor(...C2.primary!);
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "bold");
    pdf.text(`${Math.round(pct)}%`, MARGIN + CONTENT_W - 15, yPos);
    return yPos + 14;
  };

  y = drawPB(
    `Signature: ${kpis.signedDocs} of ${kpis.signedDocs + kpis.pendingSigs || 1} signed`,
    (kpis.signedDocs + kpis.pendingSigs) > 0
      ? Math.round(kpis.signedDocs / (kpis.signedDocs + kpis.pendingSigs) * 100)
      : 0,
    y,
    C.green
  );
  y = drawPB(
    `OCR: ${kpis.ocrCompleted} of ${ocrData.length || 1} completed`,
    ocrData.length > 0
      ? Math.round(kpis.ocrCompleted / ocrData.length * 100)
      : 0,
    y,
    C.amber
  );
  y = drawPB(
    `AI Indexed: ${kpis.indexed} of ${aiSearchData.length || 1}`,
    aiSearchData.length > 0
      ? Math.round(kpis.indexed / aiSearchData.length * 100)
      : 0,
    y,
    C.primary
  );
  y = Math.max(y + 16, 270);
  pdf.setDrawColor(...C2.border!);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN, y, PAGE_W - MARGIN, y);
  pdf.setTextColor(...C2.footer!);
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "normal");
  pdf.text(
    `Dashboard generated ${new Date().toLocaleString("en-US", {
      dateStyle: "long",
      timeStyle: "short",
    })}`,
    MARGIN,
    y + 7
  );
}
